meson.build: disable -Wformat-overflow on gcc with -O3
On ppc64el, where -O3 is set by default, gcc-13 gives false positives
for -Wformat-overflow in src/shared/install.c, despite an appropriate
assert() being present:

../src/shared/install.c: In function ‘install_changes_dump’:
../src/shared/install.c:434:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  434 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s does not exist.",
      |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/shared/install.c:434:75: note: format string is defined here
  434 |                         err = log_error_errno(changes[i].type, "Failed to %s unit, unit %s does not exist.",
      |                                                                           ^~
[ ... ]

To resolve the ppc64el FTBFS for now, just disable this warning when building
with -O3.

Gbp-Dch: Short