fsckd: Fix format specifiers
"cur" and "max" are size_t, so use the correct %zu macro for those
instead of %lu. Fixes warnings/errors on 32 bit architectures like

    fsckd.c:385:44: error: format ‘%lu’ expects argument of type ‘long unsigned int *’,
    but argument 5 has type ‘size_t * {aka unsigned int *}’ [-Werror=format=]