debian/tests/tests-in-lxd: use --reuse flag in lxc publish (LP: #2023229)
Since LXD 5.14, the existing command will fail with:

 Error: Aliases already exists: autopkgtest/ubuntu/...

This is because the --reuse flag was added, which we should use for this
use case.

Gbp-Dch: Short